apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-app-nodeport-service
spec:
  selector:
    app: fraud-detection-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080
  type: NodePort
