apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-app-lb-service
spec:
  selector:
    app: fraud-detection-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
