spring:
  application:
    name: FraudDetectPoc
  data: 
    redis:
      host: 54.226.160.110
      port: ${REDIS_PORT:6379}
      password: 
      timeout: 5000ms
      database: 0
      lettuce: 
        pool:
          max-active: 8 
          max-idle: 8
          min-idle: 0

aws:
  region: ${AWS_REGION:us-east-1}
  accessKeyId: 
  secretAccessKey: 

  sqs:
    queueUrl: ${AWS_SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/183150676580/my-transaction-queue.fifo}
    queueName: ${SQS_QUEUE_NAME:my-transaction-queue.fifo}

  cloudwatch:
    logGroupName: FraudDetectLogGroup
    logStreamName: FraudDetectLogStream
